export default {
    "Invalid": 0,
    "Weapon": 1,
    "Clothes": 2,
    "Props": 3,
    "Backpack": 4,
    "Drink": 5,
    "Food": 6,
    "Medicaments": 7,
    "Ammo": 8,
    "Alcohol": 9,
    "Narcotic": 10,
    "Other": 11,
    "Animal": 12,
    "Rod": 13,
    "Cage": 14,
    "GasCan": 15,
    "CarKey": 16,
    "ItemBox": 17,
    "Costume": 18,
    "KeyRing": 19,
    "Seed": 20,
    "WateringCan": 21,
    "Fertilizer": 22,
    "Coals": 23,
    "Resources": 24,
    "Ore": 25,
    "0":"Invalid",
    "1":"Weapon",
    "2":"Clothes",
    "3":"Props",
    "4":"Backpack",
    "5":"Drink",
    "6":"Food",
    "7":"Medicaments",
    "8":"Ammo",
    "9":"Alcohol",
    "10":"Narcotic",
    "11":"Other",
    "12":"Animal",
    "13":"Rod",
    "14":"Cage",
    "15":"GasCan",
    "16":"CarKey",
    "17":"ItemBox",
    "18":"Costume",
    "19":"KeyRing",
    "20":"Seed",
    "21":"WateringCan",
    "22":"Fertilizer",
    "23":"Coals",
    "24":"Resources",
    "25":"Ore",
}