export default{
    'editor_bg':'/editor/bg.mp3',
    'auth_bg':'/auth/bg.mp3',
    'hover': '/common/hover.wav',
    'click': '/common/shortClick.mp3',
    'hoverCard': '/common/hoverCard.wav',
    'click2': '/common/click2.mp3',
    'choice': '/common/choice.mp3',
    'choice2': '/common/choice2.mp3',    
    'reportMsg': '/common/msg.mp3',
    'switch': '/common/switch.wav',
    'stomach': '/common/stomach.mp3',
    'alarm': '/common/alarm.mp3',
    'radio_turn_on': '/radio/radio_turn_on.mp3',
    'radio_turn_off': '/radio/radio_turn_off.mp3',
    
    //menu
    'mainMenu': '/arena/mainmenu.mp3',
    'chooseTeam': '/arena/chooseteam.mp3',
    // quake
    'prepare': '/arena/quake/prepare.mp3',
    'play': '/arena/quake/play.mp3',
    'firstBlood': '/arena/quake/firstblood.mp3',
    'doublekill': '/arena/quake/doublekill.mp3',
    'triplekill': '/arena/quake/triplekill.mp3',
    'multikill': '/arena/quake/multikill.mp3',
    'rampage': '/arena/quake/rampage.mp3',
    'unstoppable': '/arena/quake/unstoppable.mp3',
    'ultrakill': '/arena/quake/ultrakill.mp3',
    'ludicrouskill': '/arena/quake/ludicrouskill.mp3',
    'wickedsick': '/arena/quake/wickedsick.mp3',
    'monsterkill': '/arena/quake/monsterkill.mp3',
    'holyshit': '/arena/quake/holyshit.mp3',
    'godlike': '/arena/quake/godlike.mp3',
    // gunGame
    'startGG': '/arena/gungame/gungame2.mp3',
    'levelUpGG': '/arena/gungame/smb3_powerup.mp3',
    'nadeGG': '/arena/gungame/nade_level.mp3',
    'knifeGG': '/arena/gungame/knife_level.mp3',
    'endGG': '/arena/gungame/gg_end.mp3',
    // common
    'kill': '/arena/gungame/multikill.mp3',
    // win
    'twin1': '/arena/win/twinnar1.mp3',
    'twin2': '/arena/win/twinnar2.mp3',
    'twin3': '/arena/win/twinnar3.mp3',
    'ctwin1': '/arena/win/ctwinnar1.mp3',
    'ctwin2': '/arena/win/ctwinnar2.mp3',
    'ctwin3': '/arena/win/ctwinnar3.mp3',
    // votemap
    'startyourvoting': '/arena/quake/startyourvoting.mp3',
    'gman_choose2': '/arena/quake/gman_choose2.mp3',
    'endofvote': '/arena/quake/endofvote.mp3',
    // carTunningMenu
    'tunningBg1': '/carTunningMenu/bg1.mp3',
    'tunningBg2': '/carTunningMenu/bg2.mp3',
    'tunningBg3': '/carTunningMenu/bg3.mp3',
    'tunningBg4': '/carTunningMenu/bg4.mp3',
    'tunningBg5': '/carTunningMenu/bg5.mp3',
    'tunningBg6': '/carTunningMenu/bg6.mp3',
    'tunningBg7': '/carTunningMenu/bg7.mp3',
    'tunningBg8': '/carTunningMenu/bg8.mp3',
    'tunningBg9': '/carTunningMenu/bg9.mp3',
    'tunningBg10': '/carTunningMenu/bg10.mp3',
    'tunningBg11': '/carTunningMenu/bg11.mp3',
    'tunningBg12': '/carTunningMenu/bg12.mp3',
    'tunningBg13': '/carTunningMenu/bg13.mp3',
    //School
    'autoWelcome': '/school/auto_welcome.wav',
    'autoBelt': '/school/auto_belt.wav',
    'autoStart': '/school/auto_start.wav',
    'autoLookOut': '/school/auto_look_out.wav',
    'autoArea': '/school/auto_area.wav',
    'autoCone': '/school/auto_cone.wav',
    'autoGoSchool': '/school/auto_go_school.wav',
    'motoWelcome': '/school/moto_welcome.wav',
    'motoGo': '/school/moto_go.wav',
    'motoLookOut': '/school/moto_look_out.wav',
    'motoSmellGood': '/school/moto_smell_good.wav',
    'motoMuscular': '/school/moto_muscular.wav',
    'motoThisMyNumberCallMeMaybe': '/school/moto_this_my_number_call_me_maybe.wav',
    'planeWelcome': '/school/plane_welcome.wav',
    'planeStart': '/school/plane_start.wav',
    'planeStartSecond': '/school/plane_start_second.wav',
    'planeScary': '/school/plane_scary.wav',
    'planeChassis': '/school/plane_chassis.wav',
    'planeOneLife': '/school/plane_one_life.wav',
    'heliWelcome': '/school/heli_welcome.wav',
    'goToFlyingschool': '/school/go_to_flyingschool.wav',
    'resultSurprise': '/school/result_surprise.wav',
    'examOver': '/school/exam_over.wav',
    'boatWelcome': '/school/boat_welcome.wav',
    'boatOver': '/school/boat_over.wav',
    'truckWelcome': '/school/truck_welcome.wav',

    //StartQuest
    'welcomeServer': '/startquest/welcomeServer.wav',
    'callGiveVehicle': '/startquest/callGiveVehicle.mp3',
    'meetingFriendTrevor': '/startquest/meetingFriendTrevor.wav',
    'callStealCar': '/startquest/callStealCar.wav',
    'callStealSecondCar': '/startquest/callStealSecondCar.wav',
    'police1FirstSay': '/startquest/police1FirstSay.wav',
    'police2FirstSay': '/startquest/police2FirstSay.wav',
    'police1SecondSay': '/startquest/police1SecondSay.wav',
    'judgeAdjudicates': '/startquest/judgeAdjudicates.wav',
    'courtSounds': '/startquest/courtSounds.wav',
    'goToSchool': '/startquest/goToSchool.mp3',
    'schoolCompleate': '/startquest/schoolCompleate.mp3',

    //Start sounds
    'loadCall': '/common/loadCall.mp3',
    'newYear': '/common/newYear.mp3',
    //roulette
    "tick": '/common/tick.wav',
    "roulette_win": '/roulete/win.mp3?v=3',
    "roulette_click": '/roulete/click.mp3',
    "roulette_back": '/roulete/back.mp3?v=1',
    //donateshop
    "dshop_click": '/dshop/click.mp3',
    "dshop_click2": '/dshop/click2.mp3',
    "dshop_click3": '/dshop/click3.mp3',
    "dshop_hover": '/common/hover.wav',

    //royalBattleSounds
    'demorganStartBattle': '/royalBattle/demorganStartBattle.mp3',
    'startBattle': '/royalBattle/startBattle.mp3',
    'constrictionZone': '/royalBattle/constrictionZone.mp3',

    //makeWeapon
    'makeWeaponWin': '/makeWeapon/win.mp3',   
    'makeWeaponCorrect': '/makeWeapon/correct.mp3', 
    'makeWeaponIncorrect': '/makeWeapon/incorrect.mp3',  
    'makeWeaponBonus': '/makeWeapon/bonus.mp3',  
    'makeWeaponlose': '/makeWeapon/lose.mp3',

    // Phone - Calls ringtones
    'ringtone_apex': '/phone/ringtones/ringtone_apex.mp3',
    'ringtone_beacon': '/phone/ringtones/ringtone_beacon.mp3',
    'ringtone_bulletin': '/phone/ringtones/ringtone_bulletin.mp3',
    'ringtone_cosmic': '/phone/ringtones/ringtone_cosmic.mp3',
    'ringtone_crystals': '/phone/ringtones/ringtone_crystals.mp3',
    'ringtone_hillside': '/phone/ringtones/ringtone_hillside.mp3',
    'ringtone_illuminate': '/phone/ringtones/ringtone_illuminate.mp3',
    'ringtone_presto': '/phone/ringtones/ringtone_presto.mp3',
    'ringtone_reflection': '/phone/ringtones/ringtone_reflection.mp3',

    // Phone - Notifications ringtones
    'notifications_bamboo': '/phone/notifications/notifications_bamboo.mp3',
    'notifications_bubble': '/phone/notifications/notifications_bubble.mp3',
    'notifications_chord': '/phone/notifications/notifications_chord.mp3',
    'notifications_email': '/phone/notifications/notifications_email.mp3',
    'notifications_haveamessage': '/phone/notifications/notifications_haveamessage.mp3',
    'notifications_ping': '/phone/notifications/notifications_ping.mp3',
    'notifications_sneeze': '/phone/notifications/notifications_sneeze.mp3',
    'notifications_tequila': '/phone/notifications/notifications_tequila.mp3',
    'notifications_vibro': '/phone/notifications/notifications_vibro.mp3',

    //metalPlant
    'metalPlant_meh': '/metalPlant/meh_short.mp3',
    'metalPlant_flame': '/metalPlant/flame_loop.mp3',
    'metalPlant_shot': '/metalPlant/shot_2.mp3',
    'metalPlant_tempUp': '/metalPlant/tempUp.mp3',
    'metalPlant_tempDown': '/metalPlant/tempDown.mp3',
    'metalPlant_gameOver': '/metalPlant/gameOver.mp3',
    'metalPlant_gameWin': '/metalPlant/gameWin.mp3',
    'metalPlant_boom': '/metalPlant/boom.mp3',
    'metalPlant_timer': '/metalPlant/timer.mp3',
    'metalPlant_start': '/metalPlant/start.mp3'
}