export default {
  namespaced: true,
  state: {
    show: false,
    orgList: [
      {
        id: 0,
        name: 'Ballas',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 1,
        name: 'Groove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 2,
        name: 'AHAHAHAHAHHAH',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 3,
        name: 'Lafdaf',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 4,
        name: 'Zvizdec',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 5,
        name: 'Zdraste',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 6,
        name: 'Jarko',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 7,
        name: 'Mda',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 8,
        name: 'Tsari',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 9,
        name: 'Suki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 10,
        name: 'Davki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 11,
        name: 'Papki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 12,
        name: 'Mamki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 13,
        name: 'Lox',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 14,
        name: 'Mmm',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 15,
        name: 'Aga',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 16,
        name: 'Oggi',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 17,
        name: 'Pizdes',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 18,
        name: 'Lalki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 19,
        name: 'Lolki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 20,
        name: 'Ahahaahahlol',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 21,
        name: 'Moove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 22,
        name: 'Sroove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 23,
        name: 'Kroove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 24,
        name: 'Proove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 25,
        name: 'Hihik',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 26,
        name: 'Keki',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 27,
        name: 'Test',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 28,
        name: 'Grrrrrrrrrove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
      {
        id: 29,
        name: 'Grooooove',
        owner: 'Vladimir_Putin',
        victories: 4365,
        buissCount: 45,
        membersCount: 999,
        rating: 2644,
        rank: 1,
      },
    ]
  },
  getters: {
    getFamilyRank: state => key => {
      const index = state.orgList.findIndex(item => item.id == key)
      if (index > -1)
        return state.orgList[index].rank;
      else
        return 999;
    },
  },
  mutations: {
    toggleRatingList: function(state, boolean) {
      state.RatingList.show = boolean
    },
    setOrgList: function(state, data) {
      state.orgList = data;
      state.orgList.sort((a, b) => a.rank - b.rank);
    },
    updateOrganization: function(state, data) {
      const index = state.orgList.findIndex(item => item.id == data.id)
      if (index > -1)
        state.orgList[index] = data;
      else
        state.orgList.push(data);
      state.orgList.sort((a, b) => a.rank - b.rank);
    }
  }
}
